### ISSUE TITLE
Unable to find devices

### ISSUE THREAD

**Issue by CKL1976** [paveldn/homey-mqtt-tasmota#1]
MQTT Client is configured, but unable to find any of my 10 tasmota devices. Is it required to use a specific topic ?

All other MQTT devices are working fine

**Comment by paveldn** [comment]
Hi.

When searching for devices application posts commands to group topics cmnd/sonoffs cmnd/tasmotas to get information from devices and then checking answers in stat/# topic. So your devices should be configured to use this topics. You can connect to your MQTT broker with client from your PC and check. If devices received command they should start answering with STATUS, STATUS2, STATUS6 and STATUS8 messages. In opposite case your something is wrong with Homey MQTT client.

**Comment by CKL1976** [comment]
i dont get any different result by configuring with the above....

Could you write exactly what the TOPIC and FULL TOPIC should look like ?

**Comment by paveldn** [comment]
For example one of my device settings:
![image](https://user-images.githubusercontent.com/11540146/74975467-5f723780-5427-11ea-96ae-72bd4aa9e187.png)

**Comment by CKL1976** [comment]
it works :-)

**Comment by CKL1976** [comment]
Maybe state that you need the default full topic and topic should equal name of device :-)..

**Comment by paveldn** [comment]
Thanks, Will try to add support for any custom topic configuration in future version.
