### ISSUE TITLE
[Feature] show Power usage

### ISSUE THREAD

**Issue by Radiotechniman** [paveldn/homey-mqtt-tasmota#3]
Would be nice 
I know it says so on the main page but for me it does not seem to work

**Comment by Radiotechniman** [comment]
Decided to take a look myself, it seems my tasmotas have the powerdraw in "STATUS10" 
so I cloned the repo, updated line 45 in device.js from 8 to 10 and presto, it worked. 

Now i'm not sure why this is 8 in your tasmota(s) i'm running version 8.1.0

**Comment by paveldn** [comment]
Actually it Status8 and Status10 contain the same information.  but for some reason, Status10 doesn't show when general command Status0 send.  Previously I used direct commands but to optimize code replace them with Status0 to receive all data and totally missed that Status8 did not show anymore. Thanks, I will include your fix in a new version.

**Comment by Radiotechniman** [comment]
Great, thanks!
