### ISSUE TITLE
sonoff ifan3

### ISSUE THREAD

**Issue by ZeppDK** [paveldn/homey-mqtt-tasmota#5]
hi,
is there any plans on supporting fan controls?
would really like to get an ifan3 with tasmota into homey :-)

**Comment by paveldn** [comment]
Hi,
I don't have this device on my hand so I can't test the code. Will not promise anything but will give it a try.

**Comment by ZeppDK** [comment]
Oh, that would be awsome.. 
Else i have to try and find out how to use mqtt directly 😊

**Comment by paveldn** [comment]
Added support for iFan03 in version 0.7.0
