### ISSUE TITLE
No capability for onoff in latest update

### ISSUE THREAD

**Issue by horstefan** [paveldn/homey-mqtt-tasmota#7]
Lights fail to turn on/of with latest update.

**Comment by horstefan** [comment]
![Screenshot_20210514-195931](https://user-images.githubusercontent.com/23259607/118310471-f2950280-b4ee-11eb-8cb8-f531b0811bd8.jpg)

**Comment by bartagergely** [comment]
Same here.

**Comment by horstefan** [comment]
Confirmed fix in 10.1 Thanks Pavlo!
